name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Installer les dépendances X11 et Wayland
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libwayland-bin libwayland-dev libxkbcommon-dev
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: threeal/cmake-action@v2.1.0
      with:
        build-dir: build

    - name: Configure CMake project
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build
